services:
  
  db:
    container_name: mySimpleDB
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=myDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mySimpleNetwork

  api:
    container_name: mySimpleAPI
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mySimpleNetwork
    
networks:
  mySimpleNetwork:

volumes:
  mysql_data: